# Site settings
title: mqatrombone.net
email: matthew.andrews@unthsc.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the blog of Matthew Andrews, a husband, father, systems operator/administrator/developer/engineer/architect.
  I like to learn and play video games.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mqatrombone.github.io" # the base hostname & protocol for your site
twitter_username: mqatrombone
github_username:  mqatrombone
serverfault_link: users/99275/mqatrombone

permalink: /blog/:year/:month/:day/:title/
contenturl: "/blog/content"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  excerpt_separator: <!--more-->

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
